### ISSUE TITLE
exception(pyinotify): sys_proc_fun is None 

### ISSUE THREAD

**Issue by ocehugo** [aodn/python-aodncore#191]
Maybe this is caused by version bumps or corner case not valid anymore.

Catched the exception in the pipelinebox - watcher logs:

```
2019-12-10 10:53:20,106 INFO [watchservice] creating WatchServiceContext
2019-12-10 10:53:20,113 INFO [watchservice] initialising WatchServiceManager
2019-12-10 10:53:20,114 INFO [watchservice] queuing existing file: existing_file='/var/incoming/AODN/moorings/products/IMOS_ANMN-NRS_SZ_20081120_NRSROT_FV02_PSAL-gridded-timeseries_END-20190523_C-20191121.nc'
2019-12-10 10:53:20,114 INFO [watchservice] task data: event_id='8f35182f-a305-4cee-ba50-865a335038e8' queue='MOORINGS_PRODUCTS' task_name='tasks.MOORINGS_PRODUCTS' pathname='/var/incoming/AODN/moorings/products/IMOS_ANMN-NRS_SZ_20081120_NRSROT_FV02_PSAL-gridded-timeseries_END-20190523_C-20191121.nc'
2019-12-10 10:53:20,158 INFO [watchservice] task sent: task_id='889994da-feb8-4ccb-9f91-461013de1b4f' task_name='tasks.MOORINGS_PRODUCTS' event_id='8f35182f-a305-4cee-ba50-865a335038e8' pathname='/var/incoming/AODN/moorings/products/IMOS_ANMN-NRS_SZ_20081120_NRSROT_FV02_PSAL-gridded-timeseries_END-20190523_C-20191121.nc'
2019-12-10 10:53:20,158 INFO [watchservice] adding watch for '/var/incoming/AODN/moorings/products'
2019-12-10 10:53:20,158 INFO [watchservice] active watches: ['/var/incoming/AODN/moorings/products']
2019-12-10 10:53:20,159 INFO [watchservice] starting Notifier event loop
2019-12-10 10:53:25,739 INFO [watchservice] stopping Notifier event loop. Reason: received signal '15'
2019-12-10 10:53:25,739 INFO [watchservice] stopping Notifier event loop. Reason: context manager exiting
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watchservice.py", line 29, in <module>
    main()
  File "/vagrant/src/python-aodncore/aodncore/pipeline/watchservice.py", line 25, in main
    watch_manager.notifier.loop()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/pyinotify.py", line 1376, in loop
    self.process_events()
  File "/mnt/ebs/pipeline/lib/python3.5/site-packages/pyinotify.py", line 1276, in process_events
    self._sys_proc_fun.cleanup()  # remove olds MOVED_* events records
AttributeError: 'NoneType' object has no attribute 'cleanup'
```

**Comment by mhidas** [comment]
This error occurs daily in the watchservice-stderr log, but doesn't seem to be affecting anything, so I guess it's safe to ignore (?)
@aodn/devops
