### ISSUE TITLE
Raise error if two files end up with the same dest_path

### ISSUE THREAD

**Issue by mhidas** [aodn/python-aodncore#44]
Currently it is possible for two distinct files in a collection to have different source paths, but the same file name and the same `dest_path`. The content of the files may be different. There may be rare cases where this is normal (??), but generally it implies something is wrong.

If the files are being harvested, this results in an exception like
```
2018-01-18 15:21:26,326 ERROR tasks.ANMN_NSW[aa5eb2ed-876e-4cf8-b98c-a65f4347359a] OSError: [Errno 17] File exists
Traceback (most recent call last):
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 746, in run
    self.trigger(transition['trigger'])
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 33, in get_trigger
    return func(*args, **kwargs)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 283, in trigger
    return self.machine._process(f)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 840, in _process
    return trigger()
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 313, in _trigger
    if t.execute(event_data):
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 195, in execute
    machine._callback(func, event_data)
  File "/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/transitions/core.py", line 823, in _callback
    func(*event_data.args, **event_data.kwargs)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 503, in _publish
    self._harvest(upload_runner)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/handlerbase.py", line 482, in _harvest
    harvest_runner.run(files_to_harvest)
  File "/vagrant/src/python-aodncore/aodncore/pipeline/steps/harvest.py", line 96, in run
    
  File "/vagrant/src/python-aodncore/aodncore/pipeline/steps/harvest.py", line 211, in run_additions
    for pf in matched_files:
  File "/vagrant/src/python-aodncore/aodncore/pipeline/steps/harvest.py", line 145, in create_symlink
    mkdir_p(index_dir)
OSError: [Errno 17] File exists
```
If they are not harvested but still uploaded, one will simply overwrite the other, which may not be desirable. E.g.
```
2018-01-18 15:40:39,162 INFO tasks.ANMN_NSW[49e219da-ea51-437c-ab64-8cedb321c671] uploading '/tmp/MooringsHandlerp9ZlLo/collection/IMOS_ANMN-NSW_PH100_FV01_PH100-1612_LINE_PRES_C-20170306T052820Z.png' to 'file:///s3/imos-data/IMOS/ANMN/NSW/PH100/plots/IMOS_ANMN-NSW_PH100_FV01_PH100-1612_LINE_PRES_C-20170306T052820Z.png'
2018-01-18 15:40:39,164 INFO tasks.ANMN_NSW[49e219da-ea51-437c-ab64-8cedb321c671] uploading '/tmp/MooringsHandlerp9ZlLo/collection/PH100-1612/plots/IMOS_ANMN-NSW_PH100_FV01_PH100-1612_LINE_PRES_C-20170306T052820Z.png' to 'file:///s3/imos-data/IMOS/ANMN/NSW/PH100/plots/IMOS_ANMN-NSW_PH100_FV01_PH100-1612_LINE_PRES_C-20170306T052820Z.png'
```

**Comment by mhidas** [comment]
To clarify, the required behaviour is:

Considering all files in the collection that are to be published (i.e. harvested and/or stored), after their `dest_path` attribute has been set
**if** the dest_path values are not all unique,
**then** log an error and raise an exception.

The exception should be a newly defined `DuplicateDestPathError`, a subclass of `PipelineProcessingError` (see [exceptions.py](https://github.com/aodn/python-aodncore/blob/master/aodncore/pipeline/exceptions.py)). Since this error _may_ be due to problems with the uploaded file collection, the error message will be sent to the uploaders, so needs to be understandable to them.
