### ISSUE TITLE
cannot build aodncore 0.10.2

### ISSUE THREAD

**Issue by lbesnard** [aodn/python-aodncore#81]
I wanted to build the latests aodncore which amongst others should fix the Argo pipeline on prod. 

However the build on Jenkins failed :

```Requirement already satisfied: pycparser in ./aodncore_virtualenv/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.1->paramiko==2.2.1->-r requirements.txt (line 10)) (2.18)
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from pip.req import parse_requirements
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 25, in <module>
    import pip.wheel
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/wheel.py", line 28, in <module>
    from pip.download import path_to_url, unpack_url
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 83, in <module>
    from pip._internal.compat import WINDOWS
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/home/jenkins/jobs/aodncore_build/workspace/aodncore_virtualenv/local/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor import html5lib, requests, six
ImportError: cannot import name requests
Build step 'Execute shell' marked build as failure
Archiving artifacts
Publish artifacts to S3 Bucket Build is still running
Publish artifacts to S3 Bucket Using S3 profile: iam-jenkins
Publish artifacts to S3 Bucket Skipping publishing on S3 because build failed
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE```

**Comment by lwgordonimos** [comment]
@lbesnard This is fixed, but should be in the issues repo, since it relates to the Jenkins environment and not this package.
